version: '3.8'

services:
  cassandra1:
    image: docker.io/bitnami/cassandra:5.0.2
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - 9042:9042
    volumes:
      - cassandra1_data:/bitnami
    networks:
      - cassandranet
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_SEEDS=cassandra1,cassandra2  # Seeds are correct for Docker network
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=nbd
      - CASSANDRA_PASSWORD=nbd
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra2:
    image: docker.io/bitnami/cassandra:5.0.2
    container_name: cassandra2
    hostname: cassandra2
    ports:
      - 9043:9042
    volumes:
      - cassandra2_data:/bitnami
    networks:
      - cassandranet
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_USER=nbd
      - CASSANDRA_PASSWORD=nbd
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  cassandranet:
    driver: bridge

volumes:
  cassandra1_data:
  cassandra2_data:
